### ISSUE TITLE
need rain for ice and fire lightning dragon eggs to hatch

### ISSUE THREAD

**Issue by kreezxil** [alcatrazEscapee/primal-winter#103]
I'm using the 1.16.5 version of the mod and even after whitelisting biomes, i can't spawn rain or thunder in them so that my Ice and Fire lightning dragons will hatch.

My config, btw, your default config said that "minecraft:worldgen/biome" was the way to write the biome id. However, when I did "minecraft:worldgen/savanna" it didn't work. But when I rewrote it as "minecraft:savanna" it did work. The reason I bring that up is the default toml was it written the wrong way in the sample array.

```toml
# Should the vanilla /weather be disabled? Any changes require a world restart to take effect.
disableWeatherCommand = false
# A list of biome IDs that will not be forcibly converted to frozen wastelands. Any changes requires a MC restart to take effect.
nonWinterBiomes = ["minecraft:desert", "minecraft:savanna", "minecraft:badlands"]
# A list of dimension IDs that will not have winter weather effects set.
nonWinterDimensions = ["minecraft:the_nether", "minecraft:the_end"]
# If true, the 'nonWinterBiomes' config option will be interpreted as a list of winter biomes, and all others will be ignored.
invertNonWinterBiomes = false
# If true, the 'nonWinterDimensions' config option will be interpreted as a list of winter dimensions, and all others will be ignored.
invertNonWinterDimensions = false
# If true, snow will be layered higher than one layer during world generation.
enableSnowAccumulationDuringWorldgen = true
# If true, snow will be layered higher than one layer during weather (snow).
enableSnowAccumulationDuringWeather = false

```
If by chance you're not willing to patch this on 1.16.5, and one of your later versions such as 1.20.1 supports what I need, let me know and i'll just switch my pack up to there. 

Thanks.
